# Generated by Django 3.0.7 on 2022-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrar',
            fields=[
                ('codigo_principal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo_auxiliar', models.BigIntegerField()),
                ('tipo_producto', models.IntegerField(choices=[[1, 'Bien'], [2, 'Servicio']])),
                ('nombre', models.CharField(max_length=100)),
                ('valor_unitario', models.FloatField()),
                ('iva', models.IntegerField()),
                ('ice', models.IntegerField()),
            ],
        ),
    ]
