# Generated by Django 3.0.7 on 2022-07-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
    ]
