# Generated by Django 3.0.7 on 2022-07-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20220718_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='iva',
            field=models.IntegerField(choices=[[1, '0%'], [2, '12%'], [3, '14%'], [4, 'No Objeto de Impuesto'], [5, 'Exento de IVA']]),
        ),
    ]
