# Generated by Django 3.0.7 on 2022-07-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20220718_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrar',
            new_name='Producto',
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
