# Generated by Django 3.0.7 on 2022-07-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220710_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='notice',
        ),
    ]
