# Generated by Django 3.0.7 on 2022-07-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contact_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_principal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo_auxiliar', models.BigIntegerField()),
                ('tipo_producto', models.IntegerField(choices=[[1, 'Bien'], [2, 'Servicio']])),
                ('nombre', models.CharField(max_length=100)),
                ('valor_unitario', models.FloatField()),
                ('iva', models.IntegerField(choices=[[1, '0%'], [2, '12%'], [3, '14%'], [4, 'No Objeto de Impuesto'], [5, 'Exento de IVA']])),
                ('ice', models.IntegerField()),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
