# Generated by Django 3.0.7 on 2022-07-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
